services:
    db:
        #for postgres DB
        image: "postgres:15"
        container_name: postgres_db
        ports:
            - "5432:5432"
        env_file:
            - .env
        volumes:
            - PGDATA:/var/lib/postgres/data # to persist the data if a container is restarting
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
            start_period: 10s
            interval: 5s
            timeout: 5s
            retries: 5

    api:
        #for fast API
        container_name: fast_api
        build: backend
        ports:
            - "8000:8000"
        depends_on:
            db:
                condition: service_healthy
        env_file:
            - .env
        environment:
            - HF_HOME=/tmp/hf-cache
            - UV_CACHE_DIR=/tmp/uv-cache
        volumes:
            - ./backend:/app
            - /app/.venv # to exclude the venv from restarting with every request and to keep it separate

volumes:
    PGDATA:
